### ISSUE TITLE
能支持tailwindcss吗？

### ISSUE THREAD

**Issue by CheaterScript** [hemengke1997/postcss-pxtoviewport#4]
对postcss不太熟悉，要怎么实现呢？

**Comment by hemengke1997** [comment]
直接引入tailwindcss即可，不需要额外的操作。具体参见：https://tailwindcss.com/docs/installation/using-postcss

**Comment by CheaterScript** [comment]
> 直接引入tailwindcss即可，不需要额外的操作。具体参见：https://tailwindcss.com/docs/installation/using-postcss

是我没说清楚……我用了tailwindcss和这个插件，但是tailwindcss的样式并没有被转换成viewport的单位，是我配置有问题吗？

**Comment by hemengke1997** [comment]
注意顺序，先引入 tailwindcss， 再引入此插件
